language: go
sudo: required

go:
    - 1.13

go_import_path: github.com/clearlinux/mixer-tools

env:
    - GROUP=batcheck-1
    - GROUP=batcheck-2
    - GROUP=batcheck-3
    - GROUP=batcheck-4

services:
    - docker

before_install:
    - docker build -t testdock .

script:
    - travis_wait 30 docker run -e BAT_GROUP=$GROUP testdock
